# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\rllm_inference\"]\n\rTensorRequest\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0c\n\x04step\x18\x04 \x01(\x05\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"w\n\x0eTensorResponse\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0c\n\x04step\x18\x04 \x01(\x05\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x06 \x01(\x01\" \n\rHealthRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"Z\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x14\n\x0cmemory_usage\x18\x03 \x01(\x01\x12\x11\n\tcpu_usage\x18\x04 \x01(\x01\x32\x80\x02\n\x0cLLMInference\x12L\n\rProcessTensor\x12\x1c.llm_inference.TensorRequest\x1a\x1d.llm_inference.TensorResponse\x12J\n\x0bHealthCheck\x12\x1c.llm_inference.HealthRequest\x1a\x1d.llm_inference.HealthResponse\x12V\n\x13ProcessTensorStream\x12\x1c.llm_inference.TensorRequest\x1a\x1d.llm_inference.TensorResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORREQUEST']._serialized_start=37
  _globals['_TENSORREQUEST']._serialized_end=130
  _globals['_TENSORRESPONSE']._serialized_start=132
  _globals['_TENSORRESPONSE']._serialized_end=251
  _globals['_HEALTHREQUEST']._serialized_start=253
  _globals['_HEALTHREQUEST']._serialized_end=285
  _globals['_HEALTHRESPONSE']._serialized_start=287
  _globals['_HEALTHRESPONSE']._serialized_end=377
  _globals['_LLMINFERENCE']._serialized_start=380
  _globals['_LLMINFERENCE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
