# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import grpc_service_pb2 as grpc__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMInferenceStub(object):
    """Service definition for distributed LLM inference
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTensor = channel.unary_unary(
                '/llm_inference.LLMInference/ProcessTensor',
                request_serializer=grpc__service__pb2.TensorRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.TensorResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/llm_inference.LLMInference/HealthCheck',
                request_serializer=grpc__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ProcessTensorStream = channel.stream_stream(
                '/llm_inference.LLMInference/ProcessTensorStream',
                request_serializer=grpc__service__pb2.TensorRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.TensorResponse.FromString,
                _registered_method=True)


class LLMInferenceServicer(object):
    """Service definition for distributed LLM inference
    """

    def ProcessTensor(self, request, context):
        """Send tensor data and receive processed result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessTensorStream(self, request_iterator, context):
        """Streaming interface for better performance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTensor,
                    request_deserializer=grpc__service__pb2.TensorRequest.FromString,
                    response_serializer=grpc__service__pb2.TensorResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=grpc__service__pb2.HealthRequest.FromString,
                    response_serializer=grpc__service__pb2.HealthResponse.SerializeToString,
            ),
            'ProcessTensorStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessTensorStream,
                    request_deserializer=grpc__service__pb2.TensorRequest.FromString,
                    response_serializer=grpc__service__pb2.TensorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm_inference.LLMInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm_inference.LLMInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMInference(object):
    """Service definition for distributed LLM inference
    """

    @staticmethod
    def ProcessTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm_inference.LLMInference/ProcessTensor',
            grpc__service__pb2.TensorRequest.SerializeToString,
            grpc__service__pb2.TensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm_inference.LLMInference/HealthCheck',
            grpc__service__pb2.HealthRequest.SerializeToString,
            grpc__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessTensorStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/llm_inference.LLMInference/ProcessTensorStream',
            grpc__service__pb2.TensorRequest.SerializeToString,
            grpc__service__pb2.TensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
