# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\rllm_inference\"\x85\x01\n\rTensorRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x13\n\x0b\x63ompression\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"\xb2\x01\n\x0eTensorResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x17\n\x0fprocessing_time\x18\x06 \x01(\x02\x12\x11\n\tworker_id\x18\x07 \x01(\t\x12\x0f\n\x07success\x18\x08 \x01(\x08\x12\x15\n\rerror_message\x18\t \x01(\t\" \n\rHealthRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"\x80\x01\n\x0eHealthResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cmemory_usage\x18\x03 \x01(\x02\x12\x11\n\tcpu_usage\x18\x04 \x01(\x02\x12\x0e\n\x06uptime\x18\x05 \x01(\x03\x12\x14\n\x0cmodel_loaded\x18\x06 \x01(\t2\x80\x02\n\x0cLLMInference\x12L\n\rProcessTensor\x12\x1c.llm_inference.TensorRequest\x1a\x1d.llm_inference.TensorResponse\x12V\n\x13ProcessTensorStream\x12\x1c.llm_inference.TensorRequest\x1a\x1d.llm_inference.TensorResponse(\x01\x30\x01\x12J\n\x0bHealthCheck\x12\x1c.llm_inference.HealthRequest\x1a\x1d.llm_inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORREQUEST']._serialized_start=38
  _globals['_TENSORREQUEST']._serialized_end=171
  _globals['_TENSORRESPONSE']._serialized_start=174
  _globals['_TENSORRESPONSE']._serialized_end=352
  _globals['_HEALTHREQUEST']._serialized_start=354
  _globals['_HEALTHREQUEST']._serialized_end=386
  _globals['_HEALTHRESPONSE']._serialized_start=389
  _globals['_HEALTHRESPONSE']._serialized_end=517
  _globals['_LLMINFERENCE']._serialized_start=520
  _globals['_LLMINFERENCE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
